// <auto-generated />
using System;
using HabitTracker.Server.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HabitTracker.Server.Migrations
{
    [DbContext(typeof(HabitTrackerDbContext))]
    partial class HabitTrackerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("HabitTracker.Server.Database.Entities.THabit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<uint>("StreakCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("User_id")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("User_id");

                    b.ToTable("Habits");
                });

            modelBuilder.Entity("HabitTracker.Server.Database.Entities.THabitLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Habit_id")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Habit_logged")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Length_in_days")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Start_date")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Habit_id");

                    b.ToTable("HabitLogs");
                });

            modelBuilder.Entity("HabitTracker.Server.Database.Entities.TRate", b =>
                {
                    b.Property<string>("IpAddress")
                        .HasColumnType("TEXT");

                    b.Property<uint>("Count")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Ttl")
                        .HasColumnType("TEXT");

                    b.HasKey("IpAddress");

                    b.ToTable("Rates");
                });

            modelBuilder.Entity("HabitTracker.Server.Database.Entities.TUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("HabitTracker.Server.Database.Entities.THabit", b =>
                {
                    b.HasOne("HabitTracker.Server.Database.Entities.TUser", "User")
                        .WithMany("Habits")
                        .HasForeignKey("User_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("HabitTracker.Server.Database.Entities.THabitLog", b =>
                {
                    b.HasOne("HabitTracker.Server.Database.Entities.THabit", "Habit")
                        .WithMany("HabitLogs")
                        .HasForeignKey("Habit_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Habit");
                });

            modelBuilder.Entity("HabitTracker.Server.Database.Entities.THabit", b =>
                {
                    b.Navigation("HabitLogs");
                });

            modelBuilder.Entity("HabitTracker.Server.Database.Entities.TUser", b =>
                {
                    b.Navigation("Habits");
                });
#pragma warning restore 612, 618
        }
    }
}
